In [3]:
import numpy as np

In [ ]:
# Create Arrays using numpy
# 1-D Array
arr1 = np.array([1, 2, 3, 4, 5]) # using list
print(arr1)
print(arr1.shape)

arr2 = np.array((1, 2, 3, 4, 5, 6)) # using tuple
print(arr2)
print(arr2.shape)

print(arr2.reshape(1, 6)) # converting 1D to 2D array, it means converts the array into 2D array with 1 row and it contains 6 elements

# above ,ethod does not make any permanent changes
print(arr2)
print(arr2.shape)

[1 2 3 4 5]
(5,)
[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
(6,)


In [13]:
# 2-D Array

arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
np.arange(0, 10, 2).reshape(5, 1) # creating element between 0-10 with step=2, converting it to 2-D array with 5 rows and each row contains 1 element each

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3, 4)) # create 2-D array on 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("number of dimensions : ", arr4.ndim)
print("Data type : ", arr4.dtype)
print("Size numner of elements : ", arr4.size)
print("Item size in bytes : ", arr4.itemsize)

number of dimensions :  2
Data type :  int64
Size numner of elements :  10
Item size in bytes :  8


Numpy Vectorized Operation


In [24]:
num1 = np.array([1, 2, 3, 4, 5])
num2 = np.array([10, 20, 30, 40, 50])

print("Addition : ", num1+num2)
print("Subtraction : ", num1-num2)
print("Multiplication : ", num1 * num2)
print("Division : ", num1/num2)
print("Modulus : ", num1%num2)

Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]
Modulus :  [1 2 3 4 5]


Universal Function


In [26]:
arr = np.array([2, 3, 4, 5, 6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [35]:
arr = np.arange(1, 13, 1).reshape(3, 4)
arr[1][1]


np.int64(6)

In [ ]:
# getting sub-matrix from a marix
# first choose the rows from where you want to start here it is 2nd row so we will write 1:
# then choose the column from where you want to start here it is 3rd so we will write 2:
arr[1:, 2:] 

array([[ 7,  8],
       [11, 12]])

In [40]:
arr[:2, 2:]

array([[3, 4],
       [7, 8]])

In [42]:
# Modifying array elements
arr[0, 0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [43]:
arr[1:] = 69
arr

array([[100,   2,   3,   4],
       [ 69,  69,  69,  69],
       [ 69,  69,  69,  69]])

Statistical Concepts
Normalization

In [49]:
# Normalization means converting your data in such a way that your mean is zero and standard deviation is 1
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)
median = np.median(data)

print("Mean : ", mean)
print("Median : ", median)
print("Standard Deviation : ", std_dev)
print("Variance : ", variance)

normalized_data = (data - mean) / std_dev
print("Normalized data : ", normalized_data)

Mean :  3.0
Median :  3.0
Standard Deviation :  1.4142135623730951
Variance :  2.0
Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Logical Operation


In [54]:
data = np.array([1, 2, 3, 4, 5, 10, 11, 12, 13, 14, 15])
# NumPy does element-wise comparison, returning a boolean array
# Wherever the boolean array is True, the corresponding element is selected.
print(data[data>5])
print(data[(data>=5) & (data<=13)])

# and, or, and not do not work for element-wise logical operations.
# Python’s "and" tries to evaluate the truth value of the whole array,
# but NumPy arrays can have many True/False values,
# so Python doesn’t know if the “truth” of the whole array is True or False.
# print(data[(data>=5) and (data<=13)])

[10 11 12 13 14 15]
[ 5 10 11 12 13]
